stages:
  clean_data:
    cmd: echo "smiles,ames" > data/model_input.csv && awk '{print $1","$3}' amesdata/smiles_cas_N6512.smi >> data/model_input.csv
    deps:
      - amesdata/smiles_cas_N6512.smi
    outs:
      - data/model_input.csv
  feature_generation:
    cmd: python src/generate_descriptors.py data/model_input.csv data/features.csv data/targets.csv
    deps:
      - data/model_input.csv
      - src/generate_descriptors.py
    outs:
      - data/features.csv
      - data/targets.csv
  training:
    cmd: python src/train.py data/targets.csv data/features.csv ${test_frac} data/model.pkl data/metrics.json
    deps:
      - data/model_input.csv
      - data/features.csv
      - src/train.py
    outs:
      - data/model.pkl
      - data/metrics.json
